don't run tests if only ignored paths were changed

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -21,6 +21,15 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
+      - name: Check if only ignored paths were changed
+        run: |
+          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
+          echo "Changed files: $CHANGED_FILES"
+          if [[ "$CHANGED_FILES" =~ ^(.github/|readme.html|README.md)$ ]]; then
+            echo "Only ignored files changed. Skipping CI."
+            exit 78  # Exit code 78 tells GitHub Actions to skip the job
+          fi
+      
       - name: Set up SSH
         uses: webfactory/ssh-agent@v0.9.0
         with:
